FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Proje dosyalarını kopyala
COPY ["AdessoWorldLeague.Api/AdessoWorldLeague.Api.csproj", "AdessoWorldLeague.Api/"]
COPY ["AdessoWorldLeague.Application/AdessoWorldLeague.Application.csproj", "AdessoWorldLeague.Application/"]
COPY ["AdessoWorldLeague.Domain/AdessoWorldLeague.Domain.csproj", "AdessoWorldLeague.Domain/"]
COPY ["AdessoWorldLeague.Infrastructure/AdessoWorldLeague.Infrastructure.csproj", "AdessoWorldLeague.Infrastructure/"]

# Restore işlemi
RUN dotnet restore "AdessoWorldLeague.Api/AdessoWorldLeague.Api.csproj"

# Tüm dosyaları kopyala
COPY . .

WORKDIR /src/AdessoWorldLeague.Api
RUN dotnet build "AdessoWorldLeague.Api.csproj" -c Release -o /app/build

FROM build AS publish
WORKDIR /src/AdessoWorldLeague.Api
RUN dotnet publish "AdessoWorldLeague.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AdessoWorldLeague.Api.dll"]